# Generated by Django 5.0.4 on 2024-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(max_length=6, verbose_name='地图编号')),
                ('name', models.CharField(max_length=30, verbose_name='地图名称')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='简介')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='经度')),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
