# Generated by Django 5.0.3 on 2024-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areainfo',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='areainfo',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areainfo',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=12, max_digits=6, verbose_name='经度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='地图名称'),
        ),
    ]
