# Generated by Django 5.0.3 on 2024-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_areainfo_description_areainfo_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areainfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
