# Generated by Django 5.0.3 on 2024-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_areainfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areainfo',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='name',
            field=models.CharField(max_length=30, verbose_name='地图名称'),
        ),
    ]
