# Generated by Django 5.0.3 on 2024-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_alter_areainfo_latitude_alter_areainfo_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areainfo',
            name='code',
            field=models.CharField(default=0, max_length=6, verbose_name='地图编号'),
            preserve_default=False,
        ),
    ]
