# Generated by Django 5.0.4 on 2024-04-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power_bank', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBankFeeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='费用')),
                ('paid', models.BooleanField(default=False, verbose_name='是否支付')),
                ('power_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_bank.powerbankinfo', verbose_name='充电宝')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='PowerBankRentalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('rental_date', models.DateTimeField(auto_now_add=True, verbose_name='开始日期')),
                ('power_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_bank.powerbankinfo', verbose_name='充电宝')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='PowerBankReturnInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='归还日期')),
                ('power_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_bank.powerbankinfo', verbose_name='充电宝')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='用户')),
            ],
        ),
    ]
