# Generated by Django 5.0.4 on 2024-05-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_powerbankrentalinfo_rental_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerbankfeeinfo',
            name='power_bank',
        ),
        migrations.RemoveField(
            model_name='powerbankfeeinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='powerbankreturninfo',
            name='power_bank',
        ),
        migrations.RemoveField(
            model_name='powerbankreturninfo',
            name='user',
        ),
        migrations.AddField(
            model_name='powerbankfeeinfo',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.powerbankrentalinfo', verbose_name='租赁记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerbankreturninfo',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.powerbankrentalinfo', verbose_name='租赁记录'),
            preserve_default=False,
        ),
    ]
