# Generated by Django 5.0.4 on 2024-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_powerbankfeeinfo_power_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbankrentalinfo',
            name='number',
            field=models.CharField(default=None, max_length=20, verbose_name='订单号'),
            preserve_default=False,
        ),
    ]
