# Generated by Django 5.0.4 on 2024-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_powerbankrentalinfo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbankrentalinfo',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='订单号'),
        ),
    ]
