# Generated by Django 5.0.4 on 2024-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_powerbankrentalinfo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbankrentalinfo',
            name='number',
            field=models.CharField(max_length=35, unique=True, verbose_name='订单号'),
        ),
    ]
