# Generated by Django 5.0.4 on 2024-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselChartInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('img', models.ImageField(upload_to='media/images/carousel_chart/', verbose_name='轮播图')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.SmallIntegerField(choices=[(0, '管理员公告'), (1, '维护人员公告'), (2, '全体公告')], verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
