# Generated by Django 5.0.4 on 2024-05-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0002_carouselchartinfo_create_time_and_more'),
        ('users', '0004_maintaininfo_unique_aid_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeinfo',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.accountinfo', verbose_name='发布者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticeinfo',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media/images/notice_img/', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticeinfo',
            name='content',
            field=models.CharField(max_length=100, verbose_name='内容'),
        ),
    ]
