# Generated by Django 5.0.4 on 2024-05-02 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0003_noticeinfo_aid_noticeinfo_img_and_more'),
        ('users', '0004_maintaininfo_unique_aid_area_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeinfo',
            name='aid',
        ),
        migrations.AddField(
            model_name='noticeinfo',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='发布者'),
            preserve_default=False,
        ),
    ]
