# Generated by Django 5.0.3 on 2024-04-04 09:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('account', models.CharField(max_length=15, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('identity', models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (10, '运维人员'), (11, '普通用户'), (100, '匿名用户')], default=11, verbose_name='身份')),
                ('last_login_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上次登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='uid')),
                ('username', models.CharField(default='伊莉雅', max_length=20, verbose_name='用户名')),
                ('profile', models.CharField(default='这个用户很懒，什么也没有写', max_length=100, verbose_name='个人简介')),
                ('avatar', models.ImageField(default='default.png', upload_to='media/images/avatars/', verbose_name='头像')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别')),
                ('birthday', models.DateField(default=datetime.datetime(2001, 1, 1, 0, 0), verbose_name='生日')),
                ('phone_number', models.CharField(default='0', max_length=15, verbose_name='电话号码')),
                ('aid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='users.accountinfo', verbose_name='aid')),
            ],
        ),
    ]
