# Generated by Django 5.0.4 on 2024-04-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintaininfo',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintain_info', to='users.accountinfo', verbose_name='aid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintaininfo',
            name='area_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintain_info', to='areas.areainfo', verbose_name='area_id'),
            preserve_default=False,
        ),
    ]
