# Generated by Django 5.0.3 on 2024-04-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='aid'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='新用户', max_length=20, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='MaintainInfo',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.userinfo')),
                ('areas', models.ManyToManyField(related_name='maintain_info', to='areas.areainfo', verbose_name='维护区域')),
            ],
            bases=('users.userinfo',),
        ),
    ]
