# Generated by Django 5.0.3 on 2024-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_number_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='media/images/user_avatars/', verbose_name='头像'),
        ),
    ]
