# Generated by Django 5.0.4 on 2024-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0003_alter_maintaininfo_area_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maintaininfo',
            constraint=models.UniqueConstraint(condition=models.Q(('area_id', None), _negated=True), fields=('aid', 'area_id'), name='unique_aid_area_id'),
        ),
    ]
