# Generated by Django 5.0.3 on 2024-04-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintaininfo',
            old_name='areas',
            new_name='maintain_areas',
        ),
    ]
