# Generated by Django 5.0.4 on 2024-04-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_bank', '0001_initial'),
        ('users', '0004_maintaininfo_unique_aid_area_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PowerBankMaintenance',
            new_name='PowerBankMaintenanceInfo',
        ),
    ]
