# Generated by Django 5.0.4 on 2024-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bank', '0002_rename_powerbankmaintenance_powerbankmaintenanceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbankmaintenanceinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '空闲'), (1, '充电中'), (2, '已借出'), (3, '已损坏'), (4, '已报废')], default=0, verbose_name='状态'),
        ),
    ]
