# Generated by Django 5.0.4 on 2024-04-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bank', '0003_powerbankmaintenanceinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbankmaintenanceinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(3, '已损坏'), (4, '已报废')], default=3, verbose_name='状态'),
        ),
    ]
