# Generated by Django 5.0.4 on 2024-04-28 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bank', '0004_alter_powerbankmaintenanceinfo_status'),
        ('users', '0004_maintaininfo_unique_aid_area_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbankmaintenanceinfo',
            name='maintainer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.accountinfo', verbose_name='运维人员'),
        ),
    ]
