# Generated by Django 5.0.4 on 2024-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bank', '0005_alter_powerbankmaintenanceinfo_maintainer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbankmaintenanceinfo',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理日期'),
        ),
    ]
