# Generated by Django 5.0.4 on 2024-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_bank', '0006_alter_powerbankmaintenanceinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbankmaintenanceinfo',
            name='new_status',
            field=models.SmallIntegerField(choices=[(0, '空闲'), (1, '充电中'), (2, '已借出'), (3, '已损坏'), (4, '已报废')], default=0, verbose_name='新状态'),
        ),
    ]
