# Generated by Django 5.0.4 on 2024-04-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('shop_name', models.CharField(max_length=20, verbose_name='商户名称')),
                ('address', models.CharField(max_length=30, verbose_name='详细地址')),
                ('liaison', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('shop_img', models.ImageField(upload_to='media/images/merchant_img/', verbose_name='商户图片')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.areainfo', verbose_name='所属区域')),
            ],
        ),
    ]
