# Generated by Django 5.0.3 on 2024-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='shop_name',
            field=models.CharField(max_length=20, verbose_name='商户名称'),
        ),
    ]
