# Generated by Django 5.0.4 on 2024-05-04 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('users', '0004_maintaininfo_unique_aid_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCommentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('comment', models.CharField(max_length=100, verbose_name='评论内容')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='merchants.merchantinfo', verbose_name='商户')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='merchants.merchantcommentinfo', verbose_name='父评论')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_comments', to='users.userinfo', verbose_name='用户')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
