# Generated by Django 5.0.3 on 2024-04-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchantinfo_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='address',
            field=models.CharField(max_length=30, verbose_name='详细地址'),
        ),
    ]
